version: '3'
services:
  web:
    build: ./
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
        - "8000:8000"
       
  db:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
     - .:/usr/src/app