# Generated by Django 3.2.4 on 2021-06-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Impression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_impression', models.CharField(max_length=150, verbose_name='Название места')),
                ('comment_impression', models.TextField(max_length=400, verbose_name='Коментарий о месте')),
                ('location', models.CharField(max_length=100, verbose_name='Координаты места')),
            ],
        ),
    ]
