# Generated by Django 3.2.4 on 2022-08-20 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('impression', '0003_alter_impression_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='impression',
            options={'verbose_name': 'Впечатление пользователя', 'verbose_name_plural': 'Впечатления пользователей'},
        ),
        migrations.AlterField(
            model_name='impression',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название места'),
        ),
        migrations.AlterField(
            model_name='impression',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
