# Generated by Django 3.2.4 on 2021-06-16 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(max_length=100, verbose_name='Имя пользователя')),
                ('photo_user', models.ImageField(upload_to='media/photo_user/', verbose_name='Фотография пользователя')),
            ],
        ),
    ]
